# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-first-httpd
  template:
    metadata:
      labels:
        app: my-first-httpd
    spec:
      containers:
      - name: httpd
        image: quay.io/rhn_support_dshaikh/danish/my-first2-httpd:linux
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      imagePullSecrets:
        - name: rhn-support-dshaikh-sandbox-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-first-httpd-service
spec:
  selector:
    app: my-first-httpd
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-first-httpd-route
spec:
  to:
    kind: Service
    name: my-first-httpd-service
  port:
    targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: rhn-support-dshaikh-sandbox-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbWh1WDNOMWNIQnZjblJmWkhOb1lXbHJhQ3R6WVc1a1ltOTRPakZLUTFoVlVFZENSa3cxTUZSVVVEZFRRbFZaUzBVMVdsb3pRbE0wUlZGRVJUbE1VVVZGVFZCVlFrVXpWRFJIVjFOU056VXhWbFV4TjFVM1VsZFdTRkE9IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson

